### ISSUE TITLE
Implement Output Console

### ISSUE THREAD

**Issue by nasaku898** [JoshFried/SOEN343#125]
Refactor code such that the error messages are pumped into the output console instead of an alert. 

From the pdf:

SHC will print a message in the output console when a command cannot be executed.  For example, a window cannot be opened because its path is blocked (Simulator user’s block the path of a window through the context of simulation).

[Might have to wait for SHP feature to be done] SHC will print a message to notify a user that someone broke in the house during the away mode, or after calling the police based on the time indicated by the home user.   

All commands send from this module to other modules, or to the users will be logged in the corresponding log file, and displayed in the output console

**Comment by mattfrances** [comment]
Waiting for #126 to be complete before implementing

**Comment by nasaku898** [comment]
@mattfrances you don't need to wait for #126 to start implementing the output console. There are many error messages that can be outputted to the console already. Like I mentioned before, right now we show the error message as a JavaScript alert but with the console, we could output it to their instead.
